::Launcher优先
taskkill /f /im DentalLauncher.exe
taskkill /f /im DSLauncher.exe
:: 口扫
taskkill /f /im DentalDesignAlgoService.exe
taskkill /f /im DentalCopilot.exe
taskkill /f /im ConsulReportApp.exe
taskkill /f /im MetronTrackApp.exe
taskkill /f /im ModuleTempCrownApp.exe
taskkill /f /im IBTApp.exe
taskkill /f /im SplintApp.exe
taskkill /f /im IntraoralScan.exe
taskkill /f /im AccuDesignApp.exe
taskkill /f /im DentalOrthoAppLogic.exe
taskkill /f /im OrthoApp.exe
taskkill /f /im OrthoSimApp.exe
taskkill /f /im DentalDesignAppLogic.exe
taskkill /f /im DentalScanAppLogic.exe
taskkill /f /im DentalOrderAppLogic.exe
taskkill /f /im DentalOrderDataMgr.exe
taskkill /f /im DentalAlgoService.exe
taskkill /f /im SnAuthenticator.exe
taskkill /f /im SnAIService.exe
taskkill /f /im SnSyncService.exe
taskkill /f /im DentalHub.exe
taskkill /f /im Sn3DCommunity.exe
taskkill /f /im DentalNetwork.exe
taskkill /f /im SyncServiceProc.exe
taskkill /f /im UpdateFirmwareTools.exe
taskkill /f /im DentalViewer.exe
taskkill /f /im DentalViewAppLogic.exe
taskkill /f /im FileTransfer.exe
taskkill /f /im DentalDesignCloudService.exe
taskkill /f /im DentalSphereHub.exe
taskkill /f /im DentalDesignAIService.exe
taskkill /f /im OrthoSimCommunity.exe
taskkill /f /im OrthoSimSharedMemWatcher.exe
taskkill /f /im OrthoSimAlgoService.exe
taskkill /f /im FacialAnalyserApp.exe
taskkill /f /im node.exe
taskkill /f /im DentalCopilotWinFrame.exe
taskkill /f /im DentalDesignHttpServer.exe
taskkill /f /im DentalDesignHttpServerNode.exe
:: 桌扫
taskkill /f /im DentalScan.exe
taskkill /f /im DSDesign.exe
taskkill /f /im DSAccuDesignApp.exe
taskkill /f /im DSDesignAppLogic.exe
taskkill /f /im DSScanAppLogic.exe
taskkill /f /im DSOrderAppLogic.exe
taskkill /f /im DSOrderDataMgr.exe
taskkill /f /im DSAlgoService.exe
taskkill /f /im DSSnAuthenticator.exe
taskkill /f /im DSSnSyncService.exe
taskkill /f /im DSHub.exe
taskkill /f /im SnDSCommunity.exe
taskkill /f /im DSNetwork.exe
taskkill /f /im DSUpdateFirmwareTools.exe
taskkill /f /im DSCalibrateUI.exe
taskkill /f /im DSDeviceDebugger.exe
taskkill /f /im DSViewer.exe
taskkill /f /im DSViewAppLogic.exe
exit 0
